TRANSLATIONS = {
    "en": {
        # General
        "title": "Security Report",
        "footer": "Generated by the security pipeline",

        # ZAP
        "zap_full_scan_title" : "Zap full scan report",
        "zap_api_scan_title" : "Zap API scan report",
        "site": "Site",
        "alert": "Alert",
        "description": "Description",
        "solution": "Solution",
        "references": "References",
        "confidence": "Confidence",
        "risk": "Risk",
        "risk_description": "Risk Description",
        "plugin_id": "Plugin ID",
        "alert_ref": "Alert Ref",
        "cwe_id": "CWE ID",
        "wasc_id": "WASC ID",
        "instances": "Instances",
        "instance": "Instance",
        "param": "Parameter",
        "method": "Method",
        "uri": "URI",
        "attack": "Attack",
        "evidence": "Evidence",
        "other_info": "Other Info",
        "no_alerts": "No alerts found for this site.",

        # Dependency-Check
        "dependency": "Dependency",
        "path": "Path",
        "severity": "Severity",
        "vulnerability": "Vulnerability",
        "reference": "Reference",
        "package_url": "Package Info",
        "license": "License",
        "no_dependencies": "No dependencies found in Dependency-Check report.",
        "no_vulnerable_dependencies": "No vulnerable dependencies found.",
        "unknown_file": "Unknown File",
        "unknown_path": "Unknown Path",
        "dependency_check_title": "Dependency Check Report",

        # SonarQube
        "rule": "Rule",
        "component": "Component",
        "line": "Line",
        "sonarqube_title": "SonarQube Issues",
        "no_sonarqube_issues": "No SonarQube issues found."
    },

    "sr": {
        # General
        "title": "Bezbednosni izveštaj",
        "footer": "Generisano sigurnosnim sistemom",

        # ZAP
        "zap_full_scan_title" : "Zap full scan izveštaj",
        "zap_api_scan_title" : "Zap API scan izveštaj",
        "site": "Sajt",
        "alert": "Upozorenje",
        "description": "Opis",
        "solution": "Rešenje",
        "references": "Reference",
        "confidence": "Pouzdanost",
        "risk": "Rizik",
        "risk_description": "Opis rizika",
        "plugin_id": "Plugin ID",
        "alert_ref": "Referenca upozorenja",
        "cwe_id": "CWE ID",
        "wasc_id": "WASC ID",
        "instances": "Instance",
        "instance": "Instanca",
        "param": "Parametar",
        "method": "Metod",
        "uri": "URI",
        "attack": "Napad",
        "evidence": "Dokaz",
        "other_info": "Dodatne informacije",
        "no_alerts": "Nema upozorenja za ovaj sajt.",

        # Dependency-Check
        "dependency": "Zavisnost",
        "path": "Putanja",
        "severity": "Ozbiljnost",
        "vulnerability": "Ranjivost",
        "reference": "Referenca",
        "package_url": "Informacije o paketu",
        "license": "Licenca",
        "no_dependencies": "Nema pronađenih zavisnosti u Dependency-Check izveštaju.",
        "no_vulnerable_dependencies": "Nema zavisnosti sa poznatim ranjivostima.",
        "unknown_file": "Nepoznata datoteka",
        "unknown_path": "Nepoznata putanja",
        "dependency_check_title": "Dependency-Check izveštaj",

        # SonarQube
        "rule": "Pravilo",
        "component": "Komponenta",
        "line": "Linija",
        "sonarqube_title": "SonarQube problemi",
        "no_sonarqube_issues": "Nema pronađenih problema iz SonarQube alata."
    }
}

REQUIRED_KEYS = [
    # General
    "title", "footer",

    # ZAP
    "site", "alert", "description", "solution", "references",
    "confidence", "risk", "risk_description", "plugin_id", "alert_ref",
    "cwe_id", "wasc_id", "instances", "instance", "param", "method", "uri",
    "attack", "evidence", "other_info", "no_alerts", "zap_full_scan_title", "zap_api_scan_title",

    # Dependency-Check
    "dependency", "path", "severity", "vulnerability", "reference",
    "package_url", "license", "no_dependencies", "no_vulnerable_dependencies",
    "unknown_file", "unknown_path", "dependency_check_title",

    # SonarQube
    "rule", "component", "line", "sonarqube_title", "no_sonarqube_issues"
]