services:
  digital-library-app:
    build:
      context: ..
      dockerfile: .deploy/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ../:/app

  zap:
    image: zaproxy/zap-stable
    container_name: zap
    depends_on:
      - digital-library-app
    volumes:
      - ../.zap:/zap/wrk:rw # Store ZAP data locally
      - ../.zap/reports:/zap/wrk/reports:rw # Store ZAP reports locally
    entrypoint: >
      sh -c "chmod +x /zap/wrk/start-zap.sh && /zap/wrk/start-zap.sh"
    ports:
      - "8080:8080" # ZAP API and web interface